### PR TITLE
Change kvApply logic - addresses #60

### PR DESCRIPTION
**Pull request by hafen**

### CODE REVIEW

**Comment by tcpulsipher** [comment]
I'm getting this error after installing the latest trelliscope this
morning.  I believe it has to do with the switch in logic recently made.
Hopefully it's an easy fix on your end and not something I'm doing - as I
didn't have any problems recently with makeDisplay().
Trenton

> makeDisplay(data = byMission, name = "RAWtimeSeries7KIs",
+     desc = "each Mission's 7 KIs plotted over time with Pre- and
Post-implementation dates",
+     height = 1200, width = 1920, panelFn = pf1.byMission, cogFn =
cf1.byMission)
* Validating 'panelFn'...
Error in kvApply(panelFn, kvExample(data)) : could not find function "fn"

**Comment by hafen** [comment]
Thanks!  Will fix right away.

**Comment by hafen** [comment]
Strange that this got through the Travis CI tests.  Update coming right now.

**Comment by hafen** [comment]
Give it a try now.  Should be fixed!

**Comment by tcpulsipher** [comment]
I'm still seeing the error.  Do I need to do anything differently when I
install datadr/trelliscope?
Trenton


> library(devtools)
> install_github("tesseradata/datadr")
Downloading github repo tesseradata/datadr@master
Installing datadr
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \

'/private/var/folders/62/r9dcth9s06q3m6_1t3_lcvf40000gn/T/Rtmp6QAVIw/devtools174e464b7a5c/tesseradata-datadr-95e0c83'
 \

--library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'
--install-tests

* installing *source* package ‘datadr’ ...
** R
** data
*** moving datasets to lazyload DB
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (datadr)
> install_github("tesseradata/trelliscope")
Downloading github repo tesseradata/trelliscope@master
Installing trelliscope
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \

'/private/var/folders/62/r9dcth9s06q3m6_1t3_lcvf40000gn/T/Rtmp6QAVIw/devtools174e4479237b9/tesseradata-trelliscope-dd004aa'
 \

--library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'
--install-tests

* installing *source* package ‘trelliscope’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Note: the specification for S3 class “AsIs” in package ‘RJSONIO’ seems
equivalent to one from package ‘jsonlite’: not turning on duplicate class
definitions for this class.
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Note: the specification for S3 class “AsIs” in package ‘RJSONIO’ seems
equivalent to one from package ‘jsonlite’: not turning on duplicate class
definitions for this class.
* DONE (trelliscope)


> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] matlab_1.0.2        reshape2_1.4.1      trelliscope_0.8.2.4
ggplot2_1.0.0       lattice_0.20-30     datadr_0.7.5.7      devtools_1.6.1


loaded via a namespace (and not attached):
 [1] assertthat_0.1   base64enc_0.1-2  bitops_1.0-6     chron_2.3-45
codetools_0.2-10 colorspace_1.2-4 data.table_1.9.4 DBI_0.3.1
 digest_0.6.6
[10] dplyr_0.3.0.2    fastICA_1.2-0    grid_3.1.3       gtable_0.1.2
hexbin_1.27.0    htmltools_0.2.6  httpuv_1.3.2     httr_0.6.0
jsonlite_0.9.16
[19] labeling_0.3     magrittr_1.5     MASS_7.3-39      mime_0.2
munsell_0.4.2    parallel_3.1.3   plyr_1.8.1       proto_0.3-10
R6_2.0.1
[28] Rcpp_0.11.5      RCurl_1.95-4.5   RJSONIO_1.3-0    scales_0.2.4
shiny_0.10.2.2   stringr_0.6.2    tools_3.1.3      xtable_1.7-4

**Comment by hafen** [comment]
That's interesting.  You should not get the same error.  If you exit your R session and reload things, does that fix it?

**Comment by tcpulsipher** [comment]
No it doesn't fix it.
I tested kvApply for both my panel and cog function on a subset and it
works.  However, it works when I leave out my cogFn and just use the
panelFn.  So I can live with that for now.  It's probably something on my
side, but I'm headed into a meeting at 1pm (MST) so it will be a bit before
I can look at this more closely.  Is anyone else seeing this error?
Trenton

**Comment by tcpulsipher** [comment]
I was able to get my cognostic function working.  Thanks for your help and
very quick response. I love trelliscope.
Trenton

**Pull request merged**
